export * from "./Dashboard"
export * from "./Login"
export * from "./Citas"
export * from "./Contacto"
export * from "./Odontologos"
export * from "./Pacientes"
export * from "./Servicios"
export * from "./Registro"